baseURL = "https://altarfoss.netlify.app"
title = "AltarFOSS"
copyright = "Copyright © 2020, AltarFOSS; all rights reserved."
paginate = 2
languageCode = "id-id"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-165378696-1"
DisqusShortname = "altarfoss"
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "beranda"
    name = "Beranda"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/tentang/"
    weight = 2
[[menu.main]]
        identifier = "fokus"
        name = "Fokus"
        title = "Fokus"
        weight = 3
            [[menu.main]]
                parent = "fokus"
                name = "Linux"
                url = "/tags/linux"
                weight = 1
            [[menu.main]]
                parent = "fokus"
                name = "Privasi"
                url = "/tags/privasi"
                weight = 2
            [[menu.main]]
                parent = "fokus"
                name = "Altarnatif Software"
                url = "/tag/alternatifsoftware"
                weight = 3
  

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "AltarFOSS"
  description = "Sesajen dari Pengguna Sumber Terbuka."
  homepageImage = "/images/sesajen.png"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "analytic.altarfoss@gmail.com"
    instagram = "https://stackoverflow.com"
    github = "https://github.com/altarfoss"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true 
