baseURL = "https://altarfoss.netlify.app"
title = "AltarFOSS"
copyright = "Copyright © 2020, AltarFOSS; all rights reserved."
paginate = 2
languageCode = "id-id"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "beranda"
    name = "Beranda"
    url = "/"
    weight = 10
    title = "Beranda"
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/tentang/"
    weight = 0
    title = "Tentang"
  

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "AltarFOSS"
  description = "Ini si Admin, dia gak satu."
  homepageImage = "/images/author.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "analytic.altarfoss@gmail.com"
    instagram = "https://stackoverflow.com"
    github = "https://github.com/altarfoss"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true 
